# The model arguments
model_name: UNet2d
model_kwargs:
  in_channels: 1
  out_channels: 6
  depth: 3
  initial_features: 32
  gain: 2
  final_activation: Sigmoid
  pad_convs: True

training_optimizer_kwargs:
  method: Adam
  lr: 0.0001
  weight_decay: 0.0005

devices:
  - 0
